modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/TehStoneMan/RedstoneXtra/issues"

[[mods]]
modId="redstonextra"
version="${version}"
displayName="RedstoneXtra"
updateJSONURL="http://minecraft.tehstoneman.com/redstonextra.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/restoneplusplus"
logoFile="logo.png"
authors="TehStoneMan"
description='''Redstone enhancement project.'''

[[dependencies.betterstorage]]
    modId="forge"
    mandatory=true
    versionRange="[31.2.0,)"
    ordering="NONE"
    side="BOTH"